[package]
name = "cargo-asm"
version = "0.1.3"
authors = ["gnzlbg <gonzalobg88@gmail.com>"]
description = "A cargo subcommand to disassembly Rust functions."
license = "MIT/Apache-2.0"
repository = "https://github.com/gnzlbg/cargo-asm"
homepage = "https://github.com/gnzlbg/cargo-asm"
readme = "readme.md"

[[bin]]
name = "cargo-asm"
path = "src/main.rs"

[dependencies]
structopt = "0.2.*"
walkdir = "2.*"
rustc-demangle = "0.1.*"
termcolor = "0.3.*"
edit-distance = "2.*"
serde = "1.*"
serde_json = "1.*"
serde_derive = "1.*"

[dev-dependencies]
assert_cli = "0.5"